// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvVYaI7DV3A4DZlwEhrFR-cSzWbRCDY7k',
    appId: '1:273672085385:web:bac552d84fff0729628b58',
    messagingSenderId: '273672085385',
    projectId: 'sign-language-chat-app',
    authDomain: 'sign-language-chat-app.firebaseapp.com',
    storageBucket: 'sign-language-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfF4l1hMxUTwPUH0proxHX0cnObqP0vpY',
    appId: '1:273672085385:android:ce97e27c7c9fa62f628b58',
    messagingSenderId: '273672085385',
    projectId: 'sign-language-chat-app',
    storageBucket: 'sign-language-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAxnf8oIAi_vXYkvplRtKTlcw8YXV47FY',
    appId: '1:273672085385:ios:8490773ad0f7973e628b58',
    messagingSenderId: '273672085385',
    projectId: 'sign-language-chat-app',
    storageBucket: 'sign-language-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAxnf8oIAi_vXYkvplRtKTlcw8YXV47FY',
    appId: '1:273672085385:ios:8490773ad0f7973e628b58',
    messagingSenderId: '273672085385',
    projectId: 'sign-language-chat-app',
    storageBucket: 'sign-language-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvVYaI7DV3A4DZlwEhrFR-cSzWbRCDY7k',
    appId: '1:273672085385:web:250affd3226ef781628b58',
    messagingSenderId: '273672085385',
    projectId: 'sign-language-chat-app',
    authDomain: 'sign-language-chat-app.firebaseapp.com',
    storageBucket: 'sign-language-chat-app.firebasestorage.app',
  );
}
