name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  video_player: ^2.9.0
  camera: ^0.12.0+1
  tflite_flutter: ^0.12.1
  google_mlkit_pose_detection: ^0.14.1
  permission_handler: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sign_map.json
    - assets/signs/original/
    - assets/signs/cropped/
    - assets/signs/test/
    - assets/signs/train/1_O/
dependency_overrides:
  camera_android_camerax: 0.7.2+1